schema_version: 0.2.0
slug: project-2613
project_title: Ayers Home
client_name: Of Possible Architecture
building_name: Home
phase: Design Analysis
report_date: '2026-07-18'
prepared_by: bldgtyp, llc
contact_email: ed@bldgtyp.com
target_standard: Passive House
certification_program: Design analysis only
certification_path: Not submitted
recommended_variant_id: null
building:
  address: 25 Ayers Road
  city: Westerly
  state: RI
  climate_zone: ASHRAE 5A
  building_type: single-family residential
  total_num_occupants: 6
source_files:
  phpp_path: ../07_PHPP/2613-Ayers-Home-260720.xlsx
  cad_files_received_date: null
  data_dir: data
  assets_dir: public/assets
publishing:
  production_url: https://project-2613.bldgtyp.com
  cloudflare_pages_project: bt-proj-2613-ayers-home
  access:
    mode: cloudflare_access_otp
    allowed_emails:
    - ed@bldgtyp.com
    - john@bldgtyp.com
    - carlos@ofpossible.com
    - matthew@ofpossible.com
    - vincent@ofpossible.com
narrative:
  certification:
    target: null
    ph_ach_limit: '0.6'
    phi_lcd_limit: null
    enph_hd_limit: null
    enph_per_limit: null
    enph_bg_limit: null
    enph_ag_ext_limit: null
    enph_ag_int_limit: null
    enph_uw_limit: null
    phius_hd_limit: '9.7'
    phius_cd_limit: '8.2'
    phius_hl_limit: '6.5'
    phius_cl_limit: '3.3'
    phius_nse_limit: '5725'
    phius_cfm50_limit: '0.06'
  climate:
    weather_station_name: 'US0066a-Providence :: 725070 :: PHPP (+2K summer correction)'
    weather_station_url: https://energyplus-weather.s3.amazonaws.com/north_and_central_america_wmo_region_4/USA/RI/USA_RI_Providence-T.F.Green.State.AP.725070_TMY3/USA_RI_Providence-T.F.Green.State.AP.725070_TMY3.zip
    state_name: Rhode Island
    state_name_abbreviation: RI
    ashrae_location_name: Zone 5(A)
    ashrae_design_temps: "8.5\xB0F (-13.1\xB0C)"
    ashrae_winter_design_temp_F: '8.5'
    ashrae_winter_design_temp_C: '-13.1'
  energy_code:
    name: RI Energy Conservation Code 2024
    zone: Zone 5(A)
    link: https://rules.sos.ri.gov/regulations/part/510-00-00-8
    code_base_url: https://up.codes/viewer/rhode_island/iecc-2024
    code_airtightness_url: https://up.codes/viewer/rhode_island/iecc-2024/chapter/RE_4/re-residential-energy-efficiency
    u_val_link: https://up.codes/viewer/rhode_island/iecc-2024/chapter/RE_4/re-residential-energy-efficiency
    ach_link: https://up.codes/viewer/rhode_island/iecc-2024/chapter/RE_4/re-residential-energy-efficiency
    ach_limit: '3.0'
    window_min_u_value: '0.28'
  co2:
    subregion_name: New England eGRID (2023)
    epa_subgrid_name: New England (NEWE)
    occupancy: '6'
    target_tons: '6'
    taget_co2_per_person: '4.0'
  windows:
    ph_window_u_value: null
    ph_window_r_value: null
    comfort_target_r_value: '5.6'
    comfort_target_u_value: '0.18'
  mechanical:
    erv:
      manufacturer_name: null
      type_name: null
      link: null
  user_defined: {}
